"""Create user table

Revision ID: fea110c87f80
Revises:
Create Date: 2024-02-05 08:15:27.220296

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "fea110c87f80"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "name", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_index(
        op.f("ix_user_created_at"), "user", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_user_deleted"), "user", ["deleted"], unique=False)
    op.create_index(
        op.f("ix_user_deleted_at"), "user", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=False)
    op.create_index(
        op.f("ix_user_updated_at"), "user", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_updated_at"), table_name="user")
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.drop_index(op.f("ix_user_deleted_at"), table_name="user")
    op.drop_index(op.f("ix_user_deleted"), table_name="user")
    op.drop_index(op.f("ix_user_created_at"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
