"""create job table 2

Revision ID: 1d3cfc906308
Revises:
Create Date: 2024-03-20 14:58:02.033414

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "1d3cfc906308"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "company", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "linkedin_url",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            unique=True,
        ),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column("true_remote", sa.Boolean(), nullable=False),
        sa.Column(
            "listing_remote", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("analysed", sa.Boolean(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_deleted"), "job", ["deleted"], unique=False)
    op.create_table(
        "user",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_index(op.f("ix_user_deleted"), "user", ["deleted"], unique=False)
    op.create_index(op.f("ix_user_name"), "user", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_name"), table_name="user")
    op.drop_index(op.f("ix_user_deleted"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_job_deleted"), table_name="job")
    op.drop_table("job")
    # ### end Alembic commands ###
