"""Create jobs table

Revision ID: 5c5a0c12a2c8
Revises:
Create Date: 2024-04-08 10:10:13.763729

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "5c5a0c12a2c8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "company", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "country", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "linkedin_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("applied", sa.Boolean(), nullable=False),
        sa.Column(
            "listing_remote",
            sa.Enum("ONSITE", "HYBRID", "REMOTE", name="remotestatus"),
            nullable=True,
        ),
        sa.Column("listing_date", sa.Date(), nullable=True),
        sa.Column("true_remote", sa.Boolean(), nullable=False),
        sa.Column("analysed", sa.Boolean(), nullable=True),
        sa.Column("positive_keyword_match", sa.Boolean(), nullable=True),
        sa.Column("negative_keyword_match", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("linkedin_url"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job")
    # ### end Alembic commands ###
