"""Make country in job nullable to support ats pages

Revision ID: 3cf17d40f615
Revises: 85ddbb56d697
Create Date: 2025-12-22 13:41:28.969349

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "3cf17d40f615"
down_revision = "85ddbb56d697"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("job", "country", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("job", "country", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
