"""Update job with remote flag reason attribute

Revision ID: 85ddbb56d697
Revises: ad96a0e3fd9a
Create Date: 2025-12-06 14:57:29.641533

"""

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "85ddbb56d697"
down_revision = "ad96a0e3fd9a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("career_page")
    op.add_column(
        "job",
        sa.Column(
            "remote_flag_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "remote_flag_reason")
    op.create_table(
        "career_page",
        sa.Column("company_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("ats_provider", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="career_page_pkey"),
        sa.UniqueConstraint("url", name="career_page_url_key"),
    )
    # ### end Alembic commands ###
