"""Add career page model

Revision ID: ad96a0e3fd9a
Revises: 5c5a0c12a2c8
Create Date: 2025-10-23 09:58:59.236844

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ad96a0e3fd9a"
down_revision = "5c5a0c12a2c8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "career_page",
        sa.Column("company_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="career_page_pkey"),
        sa.UniqueConstraint("url", name="career_page_url_key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("career_page")
    # ### end Alembic commands ###
