"""add user_job mapping table

Revision ID: cf19de7f0b44
Revises: c11a1b91cd0a
Create Date: 2026-01-16 14:21:30.794163

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "cf19de7f0b44"
down_revision = "c11a1b91cd0a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_job",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "applied", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "ignored", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "job_id"),
    )
    op.create_index(op.f("ix_user_job_job_id"), "user_job", ["job_id"], unique=False)
    op.create_index(op.f("ix_user_job_user_id"), "user_job", ["user_id"], unique=False)
    op.drop_column("job", "applied")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job",
        sa.Column(
            "applied",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_user_job_user_id"), table_name="user_job")
    op.drop_index(op.f("ix_user_job_job_id"), table_name="user_job")
    op.drop_table("user_job")
    # ### end Alembic commands ###
