"""Add unknown remote status

Revision ID: e71265f24e2d
Revises: 4d2c9a7b1f0e
Create Date: 2026-02-03 13:01:58.295118

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "e71265f24e2d"
down_revision = "4d2c9a7b1f0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.sync_enum_values(
        "public",
        "remotestatus",
        ["HYBRID", "ONSITE", "REMOTE"],
        ["HYBRID", "ONSITE", "REMOTE", "UNKNOWN"],
        [("job", "listing_remote")],
        False,
    )
    op.sync_enum_values(
        "public",
        "source",
        [
            "ASHBY",
            "BAMBOO",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBED",
            "GREENHOUSE_EMBEDDED",
            "HIBOB",
            "LEVER",
            "LINKEDIN",
            "PERSONIO",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [
            "ASHBY",
            "BAMBOO",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBEDDED",
            "HIBOB",
            "LEVER",
            "LINKEDIN",
            "PERSONIO",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [("job", "source")],
        False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "source",
        [
            "ASHBY",
            "BAMBOO",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBEDDED",
            "HIBOB",
            "LEVER",
            "LINKEDIN",
            "PERSONIO",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [
            "ASHBY",
            "BAMBOO",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBED",
            "GREENHOUSE_EMBEDDED",
            "HIBOB",
            "LEVER",
            "LINKEDIN",
            "PERSONIO",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [("job", "source")],
        True,
    )
    op.sync_enum_values(
        "public",
        "remotestatus",
        ["HYBRID", "ONSITE", "REMOTE", "UNKNOWN"],
        ["HYBRID", "ONSITE", "REMOTE"],
        [("job", "listing_remote")],
        True,
    )
    # ### end Alembic commands ###
