"""Add personio scraper

Revision ID: 378e9db4feb3
Revises: cf19de7f0b44
Create Date: 2026-01-27 16:18:33.783077

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "378e9db4feb3"
down_revision = "cf19de7f0b44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "source",
        [
            "ASHBY",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBED",
            "GREENHOUSE_EMBEDDED",
            "LEVER",
            "LINKEDIN",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [
            "ASHBY",
            "BAMBOO",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBEDDED",
            "HIBOB",
            "LEVER",
            "LINKEDIN",
            "PERSONIO",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [("job", "source")],
        False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "source",
        [
            "ASHBY",
            "BAMBOO",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBEDDED",
            "HIBOB",
            "LEVER",
            "LINKEDIN",
            "PERSONIO",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [
            "ASHBY",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBED",
            "GREENHOUSE_EMBEDDED",
            "LEVER",
            "LINKEDIN",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [("job", "source")],
        True,
    )
    # ### end Alembic commands ###
