"""Add to job source enum

Revision ID: a283b67eaddb
Revises: b003b7edbdd9
Create Date: 2026-01-05 13:09:49.246667

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "a283b67eaddb"
down_revision = "b003b7edbdd9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "source",
        [
            "ASHBY",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBED",
            "LEVER",
            "LINKEDIN",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [
            "ASHBY",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBEDDED",
            "LEVER",
            "LINKEDIN",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [("job", "source")],
        False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "source",
        [
            "ASHBY",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBEDDED",
            "LEVER",
            "LINKEDIN",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [
            "ASHBY",
            "GREENHOUSE_BOARD",
            "GREENHOUSE_EMBED",
            "LEVER",
            "LINKEDIN",
            "RECRUITEE",
            "RIPPLING",
            "TEAMTAILOR",
        ],
        [("job", "source")],
        True,
    )
    # ### end Alembic commands ###
